# RED A

# HOSTS
ha[0]=red_a

# ROUTER
ra[0]=red_a
ra[1]=red_f
ra[2]=red_i

#----------------------------

# RED B

# HOSTS
hb[0]=red_b

# ROUTER
rb[0]=red_b
rb[1]=red_f
rb[2]=red_g
rb[3]=red_j

#----------------------------

# RED C

# HOSTS
hc[0]=red_c

# ROUTER
rc[0]=red_c
rc[1]=red_i
rc[2]=red_h
rc[3]=red_l

#----------------------------

# RED D

# HOSTS
hd[0]=red_d

# ROUTER
rd[0]=red_d
rd[1]=red_l
rd[2]=red_j

#----------------------------

# ROUTER RE

re[0]=red_h
re[1]=red_g
re[2]=red_k